services:
  - type: web
    name: Common Credits
    env: node
    region: ohio
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node build/index.js
    autoDeploy: false